language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
  - pip install -r requirements.txt
script:
  - python -m pytest simulation/test
