# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ast.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ast.proto',
  package='messages',
  serialized_pb=_b('\n\tast.proto\x12\x08messages\"\x16\n\x07IdState\x12\x0b\n\x03val\x18\x01 \x02(\x05\"\x1d\n\x0eIdPrecondition\x12\x0b\n\x03val\x18\x01 \x02(\x05\"\x14\n\x05IdVar\x12\x0b\n\x03val\x18\x01 \x02(\x05\"\x1a\n\x0bProbability\x12\x0b\n\x03val\x18\x01 \x02(\x02\"_\n\x0c\x41\x63tionCngVar\x12#\n\x04prob\x18\x01 \x02(\x0b\x32\x15.messages.Probability\x12\x1f\n\x06id_var\x18\x02 \x02(\x0b\x32\x0f.messages.IdVar\x12\t\n\x01\x62\x18\x03 \x02(\x08\"Z\n\x0e\x41\x63tionCngState\x12#\n\x04prob\x18\x01 \x02(\x0b\x32\x15.messages.Probability\x12#\n\x08id_state\x18\x02 \x02(\x0b\x32\x11.messages.IdState\"^\n\x06\x41\x63tion\x12+\n\tcng_state\x18\x01 \x02(\x0b\x32\x18.messages.ActionCngState\x12\'\n\x07\x63ng_var\x18\x02 \x02(\x0b\x32\x16.messages.ActionCngVar\"T\n\x14PreviousPrecondition\x12\x31\n\x0fid_precondition\x18\x01 \x02(\x0b\x32\x18.messages.IdPrecondition\x12\t\n\x01\x62\x18\x02 \x02(\x08\"4\n\rPreviousState\x12#\n\x08id_state\x18\x01 \x02(\x0b\x32\x11.messages.IdState\"+\n\x07\x41\x63tions\x12 \n\x06\x61_list\x18\x01 \x03(\x0b\x32\x10.messages.Action\"H\n\x15PreviousPreconditions\x12/\n\x07pc_list\x18\x01 \x03(\x0b\x32\x1e.messages.PreviousPrecondition\":\n\x0ePreviousStates\x12(\n\x07ps_list\x18\x01 \x03(\x0b\x32\x17.messages.PreviousState\"\x86\x01\n\x04Rule\x12)\n\x07pc_list\x18\x01 \x02(\x0b\x32\x18.messages.PreviousStates\x12\x30\n\x07ps_list\x18\x02 \x02(\x0b\x32\x1f.messages.PreviousPreconditions\x12!\n\x06\x61_list\x18\x03 \x02(\x0b\x32\x11.messages.Actions\"(\n\x07RuleSet\x12\x1d\n\x05rules\x18\x01 \x03(\x0b\x32\x0e.messages.Rule\"P\n\x0fStateInitialize\x12\x13\n\x0bprob_init_1\x18\x01 \x02(\x02\x12\x13\n\x0bprob_init_2\x18\x02 \x02(\x02\x12\x13\n\x0bprob_init_3\x18\x03 \x02(\x02\"S\n\x04Root\x12\'\n\x04init\x18\x01 \x02(\x0b\x32\x19.messages.StateInitialize\x12\"\n\x07ruleset\x18\x02 \x02(\x0b\x32\x11.messages.RuleSet\"\'\n\x03\x41ST\x12 \n\x08\x61st_root\x18\x01 \x02(\x0b\x32\x0e.messages.Root')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_IDSTATE = _descriptor.Descriptor(
  name='IdState',
  full_name='messages.IdState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='messages.IdState.val', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=45,
)


_IDPRECONDITION = _descriptor.Descriptor(
  name='IdPrecondition',
  full_name='messages.IdPrecondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='messages.IdPrecondition.val', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=76,
)


_IDVAR = _descriptor.Descriptor(
  name='IdVar',
  full_name='messages.IdVar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='messages.IdVar.val', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=98,
)


_PROBABILITY = _descriptor.Descriptor(
  name='Probability',
  full_name='messages.Probability',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='messages.Probability.val', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=126,
)


_ACTIONCNGVAR = _descriptor.Descriptor(
  name='ActionCngVar',
  full_name='messages.ActionCngVar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prob', full_name='messages.ActionCngVar.prob', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_var', full_name='messages.ActionCngVar.id_var', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='messages.ActionCngVar.b', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=223,
)


_ACTIONCNGSTATE = _descriptor.Descriptor(
  name='ActionCngState',
  full_name='messages.ActionCngState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prob', full_name='messages.ActionCngState.prob', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id_state', full_name='messages.ActionCngState.id_state', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=315,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='messages.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cng_state', full_name='messages.Action.cng_state', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cng_var', full_name='messages.Action.cng_var', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=411,
)


_PREVIOUSPRECONDITION = _descriptor.Descriptor(
  name='PreviousPrecondition',
  full_name='messages.PreviousPrecondition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_precondition', full_name='messages.PreviousPrecondition.id_precondition', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='b', full_name='messages.PreviousPrecondition.b', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=497,
)


_PREVIOUSSTATE = _descriptor.Descriptor(
  name='PreviousState',
  full_name='messages.PreviousState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_state', full_name='messages.PreviousState.id_state', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=551,
)


_ACTIONS = _descriptor.Descriptor(
  name='Actions',
  full_name='messages.Actions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a_list', full_name='messages.Actions.a_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=553,
  serialized_end=596,
)


_PREVIOUSPRECONDITIONS = _descriptor.Descriptor(
  name='PreviousPreconditions',
  full_name='messages.PreviousPreconditions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pc_list', full_name='messages.PreviousPreconditions.pc_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=598,
  serialized_end=670,
)


_PREVIOUSSTATES = _descriptor.Descriptor(
  name='PreviousStates',
  full_name='messages.PreviousStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ps_list', full_name='messages.PreviousStates.ps_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=730,
)


_RULE = _descriptor.Descriptor(
  name='Rule',
  full_name='messages.Rule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pc_list', full_name='messages.Rule.pc_list', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ps_list', full_name='messages.Rule.ps_list', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='a_list', full_name='messages.Rule.a_list', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=867,
)


_RULESET = _descriptor.Descriptor(
  name='RuleSet',
  full_name='messages.RuleSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rules', full_name='messages.RuleSet.rules', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=869,
  serialized_end=909,
)


_STATEINITIALIZE = _descriptor.Descriptor(
  name='StateInitialize',
  full_name='messages.StateInitialize',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prob_init_1', full_name='messages.StateInitialize.prob_init_1', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob_init_2', full_name='messages.StateInitialize.prob_init_2', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob_init_3', full_name='messages.StateInitialize.prob_init_3', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=911,
  serialized_end=991,
)


_ROOT = _descriptor.Descriptor(
  name='Root',
  full_name='messages.Root',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='init', full_name='messages.Root.init', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ruleset', full_name='messages.Root.ruleset', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=993,
  serialized_end=1076,
)


_AST = _descriptor.Descriptor(
  name='AST',
  full_name='messages.AST',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ast_root', full_name='messages.AST.ast_root', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1078,
  serialized_end=1117,
)

_ACTIONCNGVAR.fields_by_name['prob'].message_type = _PROBABILITY
_ACTIONCNGVAR.fields_by_name['id_var'].message_type = _IDVAR
_ACTIONCNGSTATE.fields_by_name['prob'].message_type = _PROBABILITY
_ACTIONCNGSTATE.fields_by_name['id_state'].message_type = _IDSTATE
_ACTION.fields_by_name['cng_state'].message_type = _ACTIONCNGSTATE
_ACTION.fields_by_name['cng_var'].message_type = _ACTIONCNGVAR
_PREVIOUSPRECONDITION.fields_by_name['id_precondition'].message_type = _IDPRECONDITION
_PREVIOUSSTATE.fields_by_name['id_state'].message_type = _IDSTATE
_ACTIONS.fields_by_name['a_list'].message_type = _ACTION
_PREVIOUSPRECONDITIONS.fields_by_name['pc_list'].message_type = _PREVIOUSPRECONDITION
_PREVIOUSSTATES.fields_by_name['ps_list'].message_type = _PREVIOUSSTATE
_RULE.fields_by_name['pc_list'].message_type = _PREVIOUSSTATES
_RULE.fields_by_name['ps_list'].message_type = _PREVIOUSPRECONDITIONS
_RULE.fields_by_name['a_list'].message_type = _ACTIONS
_RULESET.fields_by_name['rules'].message_type = _RULE
_ROOT.fields_by_name['init'].message_type = _STATEINITIALIZE
_ROOT.fields_by_name['ruleset'].message_type = _RULESET
_AST.fields_by_name['ast_root'].message_type = _ROOT
DESCRIPTOR.message_types_by_name['IdState'] = _IDSTATE
DESCRIPTOR.message_types_by_name['IdPrecondition'] = _IDPRECONDITION
DESCRIPTOR.message_types_by_name['IdVar'] = _IDVAR
DESCRIPTOR.message_types_by_name['Probability'] = _PROBABILITY
DESCRIPTOR.message_types_by_name['ActionCngVar'] = _ACTIONCNGVAR
DESCRIPTOR.message_types_by_name['ActionCngState'] = _ACTIONCNGSTATE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['PreviousPrecondition'] = _PREVIOUSPRECONDITION
DESCRIPTOR.message_types_by_name['PreviousState'] = _PREVIOUSSTATE
DESCRIPTOR.message_types_by_name['Actions'] = _ACTIONS
DESCRIPTOR.message_types_by_name['PreviousPreconditions'] = _PREVIOUSPRECONDITIONS
DESCRIPTOR.message_types_by_name['PreviousStates'] = _PREVIOUSSTATES
DESCRIPTOR.message_types_by_name['Rule'] = _RULE
DESCRIPTOR.message_types_by_name['RuleSet'] = _RULESET
DESCRIPTOR.message_types_by_name['StateInitialize'] = _STATEINITIALIZE
DESCRIPTOR.message_types_by_name['Root'] = _ROOT
DESCRIPTOR.message_types_by_name['AST'] = _AST

IdState = _reflection.GeneratedProtocolMessageType('IdState', (_message.Message,), dict(
  DESCRIPTOR = _IDSTATE,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.IdState)
  ))
_sym_db.RegisterMessage(IdState)

IdPrecondition = _reflection.GeneratedProtocolMessageType('IdPrecondition', (_message.Message,), dict(
  DESCRIPTOR = _IDPRECONDITION,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.IdPrecondition)
  ))
_sym_db.RegisterMessage(IdPrecondition)

IdVar = _reflection.GeneratedProtocolMessageType('IdVar', (_message.Message,), dict(
  DESCRIPTOR = _IDVAR,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.IdVar)
  ))
_sym_db.RegisterMessage(IdVar)

Probability = _reflection.GeneratedProtocolMessageType('Probability', (_message.Message,), dict(
  DESCRIPTOR = _PROBABILITY,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.Probability)
  ))
_sym_db.RegisterMessage(Probability)

ActionCngVar = _reflection.GeneratedProtocolMessageType('ActionCngVar', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONCNGVAR,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.ActionCngVar)
  ))
_sym_db.RegisterMessage(ActionCngVar)

ActionCngState = _reflection.GeneratedProtocolMessageType('ActionCngState', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONCNGSTATE,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.ActionCngState)
  ))
_sym_db.RegisterMessage(ActionCngState)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), dict(
  DESCRIPTOR = _ACTION,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.Action)
  ))
_sym_db.RegisterMessage(Action)

PreviousPrecondition = _reflection.GeneratedProtocolMessageType('PreviousPrecondition', (_message.Message,), dict(
  DESCRIPTOR = _PREVIOUSPRECONDITION,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.PreviousPrecondition)
  ))
_sym_db.RegisterMessage(PreviousPrecondition)

PreviousState = _reflection.GeneratedProtocolMessageType('PreviousState', (_message.Message,), dict(
  DESCRIPTOR = _PREVIOUSSTATE,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.PreviousState)
  ))
_sym_db.RegisterMessage(PreviousState)

Actions = _reflection.GeneratedProtocolMessageType('Actions', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONS,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.Actions)
  ))
_sym_db.RegisterMessage(Actions)

PreviousPreconditions = _reflection.GeneratedProtocolMessageType('PreviousPreconditions', (_message.Message,), dict(
  DESCRIPTOR = _PREVIOUSPRECONDITIONS,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.PreviousPreconditions)
  ))
_sym_db.RegisterMessage(PreviousPreconditions)

PreviousStates = _reflection.GeneratedProtocolMessageType('PreviousStates', (_message.Message,), dict(
  DESCRIPTOR = _PREVIOUSSTATES,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.PreviousStates)
  ))
_sym_db.RegisterMessage(PreviousStates)

Rule = _reflection.GeneratedProtocolMessageType('Rule', (_message.Message,), dict(
  DESCRIPTOR = _RULE,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.Rule)
  ))
_sym_db.RegisterMessage(Rule)

RuleSet = _reflection.GeneratedProtocolMessageType('RuleSet', (_message.Message,), dict(
  DESCRIPTOR = _RULESET,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.RuleSet)
  ))
_sym_db.RegisterMessage(RuleSet)

StateInitialize = _reflection.GeneratedProtocolMessageType('StateInitialize', (_message.Message,), dict(
  DESCRIPTOR = _STATEINITIALIZE,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.StateInitialize)
  ))
_sym_db.RegisterMessage(StateInitialize)

Root = _reflection.GeneratedProtocolMessageType('Root', (_message.Message,), dict(
  DESCRIPTOR = _ROOT,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.Root)
  ))
_sym_db.RegisterMessage(Root)

AST = _reflection.GeneratedProtocolMessageType('AST', (_message.Message,), dict(
  DESCRIPTOR = _AST,
  __module__ = 'ast_pb2'
  # @@protoc_insertion_point(class_scope:messages.AST)
  ))
_sym_db.RegisterMessage(AST)


# @@protoc_insertion_point(module_scope)
