# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='messages',
  serialized_pb=_b('\n\x0csimple.proto\x12\x08messages\"q\n\x0cOuterMessage\x12\x1f\n\x07state_1\x18\x01 \x02(\x0e\x32\x0e.messages.Test\x12\x1f\n\x07state_2\x18\x02 \x02(\x0e\x32\x0e.messages.Test\x12\x1f\n\x07state_3\x18\x03 \x02(\x0e\x32\x0e.messages.Test\"/\n\x04Root\x12\'\n\x07message\x18\x01 \x02(\x0b\x32\x16.messages.OuterMessage*-\n\x04Test\x12\x0b\n\x07STATE_0\x10\x00\x12\x0b\n\x07STATE_1\x10\x01\x12\x0b\n\x07STATE_2\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TEST = _descriptor.EnumDescriptor(
  name='Test',
  full_name='messages.Test',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STATE_0', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_1', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATE_2', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=190,
  serialized_end=235,
)
_sym_db.RegisterEnumDescriptor(_TEST)

Test = enum_type_wrapper.EnumTypeWrapper(_TEST)
STATE_0 = 0
STATE_1 = 1
STATE_2 = 2



_OUTERMESSAGE = _descriptor.Descriptor(
  name='OuterMessage',
  full_name='messages.OuterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_1', full_name='messages.OuterMessage.state_1', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_2', full_name='messages.OuterMessage.state_2', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_3', full_name='messages.OuterMessage.state_3', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=139,
)


_ROOT = _descriptor.Descriptor(
  name='Root',
  full_name='messages.Root',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='messages.Root.message', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=188,
)

_OUTERMESSAGE.fields_by_name['state_1'].enum_type = _TEST
_OUTERMESSAGE.fields_by_name['state_2'].enum_type = _TEST
_OUTERMESSAGE.fields_by_name['state_3'].enum_type = _TEST
_ROOT.fields_by_name['message'].message_type = _OUTERMESSAGE
DESCRIPTOR.message_types_by_name['OuterMessage'] = _OUTERMESSAGE
DESCRIPTOR.message_types_by_name['Root'] = _ROOT
DESCRIPTOR.enum_types_by_name['Test'] = _TEST

OuterMessage = _reflection.GeneratedProtocolMessageType('OuterMessage', (_message.Message,), dict(
  DESCRIPTOR = _OUTERMESSAGE,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:messages.OuterMessage)
  ))
_sym_db.RegisterMessage(OuterMessage)

Root = _reflection.GeneratedProtocolMessageType('Root', (_message.Message,), dict(
  DESCRIPTOR = _ROOT,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:messages.Root)
  ))
_sym_db.RegisterMessage(Root)


# @@protoc_insertion_point(module_scope)
