<rules_expansion> ::= <rules><rules_expansion>|<rules>
<rules> ::= <preconditions><behaviors><actions>
<preconditions_expansion> ::= <preconditions><preconditions_expansion>|e
<behaviors_expansion> ::= <behaviors><behaviors_expansion>|e
<actions_expansion> ::= <actions><actions_expansion>|<actions>
<preconditions> ::= <precondition_name>|<precondition_name>
<behaviors> ::= <behaviors_name>
<actions> ::= <actions_behavioral>|<actions_internal_state>
<actions_behavioral> ::= p,<behaviors_name>
<actions_internal_state> ::= p,<internal_state_name>