.PHONY: 

all: config

config:
	cp agent.json ~/ARGoS/iAnt-ARGoS-master/experiments/agent.json
	cp ga.json ~/ARGoS/iAnt-ARGoS-master/experiments/ga.json

clean:
	rm -f ~/ARGoS/iAnt-ARGoS-master/experiments/agent.json
	rm -f ~/ARGoS/iAnt-ARGoS-master/experiments/ga.json
	