.PHONY: 

all: config

config:
	cp agentdescriptor.json ~/ARGoS/iAnt-ARGoS-master/experiments/agentdescriptor.json
	cp gadescriptor.json ~/ARGoS/iAnt-ARGoS-master/experiments/gadescriptor.json

clean:
	rm -f ~/ARGoS/iAnt-ARGoS-master/experiments/agentdescriptor.json
	rm -f ~/ARGoS/iAnt-ARGoS-master/experiments/gadescriptor.json
	