# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='agent.proto',
  package='agent',
  serialized_pb=_b('\n\x0b\x61gent.proto\x12\x05\x61gent\"\xbd\x01\n\x08Genotype\x12)\n!probabilityOfSwitchingToSearching\x18\x01 \x02(\x02\x12$\n\x1cprobabilityOfReturningToNest\x18\x02 \x02(\x02\x12!\n\x19uninformedSearchVariation\x18\x03 \x02(\x02\x12!\n\x19rateOfInformedSearchDecay\x18\x04 \x02(\x02\x12\x1a\n\x12rateOfSiteFidelity\x18\x05 \x02(\x02\";\n\x05\x41gent\x12!\n\x08genotype\x18\x01 \x02(\x0b\x32\x0f.agent.Genotype\x12\x0f\n\x07\x66itness\x18\x02 \x02(\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GENOTYPE = _descriptor.Descriptor(
  name='Genotype',
  full_name='agent.Genotype',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='probabilityOfSwitchingToSearching', full_name='agent.Genotype.probabilityOfSwitchingToSearching', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='probabilityOfReturningToNest', full_name='agent.Genotype.probabilityOfReturningToNest', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uninformedSearchVariation', full_name='agent.Genotype.uninformedSearchVariation', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rateOfInformedSearchDecay', full_name='agent.Genotype.rateOfInformedSearchDecay', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rateOfSiteFidelity', full_name='agent.Genotype.rateOfSiteFidelity', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=212,
)


_AGENT = _descriptor.Descriptor(
  name='Agent',
  full_name='agent.Agent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='genotype', full_name='agent.Agent.genotype', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fitness', full_name='agent.Agent.fitness', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=273,
)

_AGENT.fields_by_name['genotype'].message_type = _GENOTYPE
DESCRIPTOR.message_types_by_name['Genotype'] = _GENOTYPE
DESCRIPTOR.message_types_by_name['Agent'] = _AGENT

Genotype = _reflection.GeneratedProtocolMessageType('Genotype', (_message.Message,), dict(
  DESCRIPTOR = _GENOTYPE,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Genotype)
  ))
_sym_db.RegisterMessage(Genotype)

Agent = _reflection.GeneratedProtocolMessageType('Agent', (_message.Message,), dict(
  DESCRIPTOR = _AGENT,
  __module__ = 'agent_pb2'
  # @@protoc_insertion_point(class_scope:agent.Agent)
  ))
_sym_db.RegisterMessage(Agent)


# @@protoc_insertion_point(module_scope)
