# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: econ.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='econ.proto',
  package='proto',
  serialized_pb=_b('\n\necon.proto\x12\x05proto\"1\n\x04Item\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0f\n\x07\x64\x65\x66\x65nse\x18\x03 \x01(\x05\"5\n\tInventory\x12\x0c\n\x04\x63oin\x18\x01 \x02(\x05\x12\x1a\n\x05items\x18\x02 \x03(\x0b\x32\x0b.proto.Item\"\x8a\x01\n\x08Strategy\x12\x0e\n\x06param1\x18\x01 \x02(\x01\x12\x0e\n\x06param2\x18\x02 \x02(\x01\x12\x0e\n\x06param3\x18\x03 \x02(\x01\x12\x0e\n\x06param4\x18\x04 \x02(\x01\x12\x0e\n\x06param5\x18\x05 \x02(\x01\x12\x0e\n\x06param6\x18\x06 \x02(\x01\x12\x0e\n\x06param7\x18\x07 \x02(\x01\x12\x0e\n\x06param8\x18\x08 \x02(\x01\"`\n\tEconAgent\x12\x0b\n\x03\x61id\x18\x01 \x02(\x05\x12#\n\tinventory\x18\x02 \x02(\x0b\x32\x10.proto.Inventory\x12!\n\x08strategy\x18\x03 \x02(\x0b\x32\x0f.proto.Strategy\",\n\nIngredient\x12\x0f\n\x07item_id\x18\x01 \x02(\x05\x12\r\n\x05\x63ount\x18\x02 \x02(\x05\"T\n\x06Recipe\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x16\n\x0eoutput_item_id\x18\x02 \x02(\x05\x12&\n\x0bingredients\x18\x03 \x03(\x0b\x32\x11.proto.Ingredient\"m\n\x05World\x12\x1b\n\x06\x61rmors\x18\x01 \x03(\x0b\x32\x0b.proto.Item\x12\'\n\x12\x63rafting_materials\x18\x02 \x03(\x0b\x32\x0b.proto.Item\x12\x1e\n\x07recipes\x18\x03 \x03(\x0b\x32\r.proto.Recipe')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='proto.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='proto.Item.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defense', full_name='proto.Item.defense', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=70,
)


_INVENTORY = _descriptor.Descriptor(
  name='Inventory',
  full_name='proto.Inventory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='coin', full_name='proto.Inventory.coin', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='proto.Inventory.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=125,
)


_STRATEGY = _descriptor.Descriptor(
  name='Strategy',
  full_name='proto.Strategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='param1', full_name='proto.Strategy.param1', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param2', full_name='proto.Strategy.param2', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param3', full_name='proto.Strategy.param3', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param4', full_name='proto.Strategy.param4', index=3,
      number=4, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param5', full_name='proto.Strategy.param5', index=4,
      number=5, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param6', full_name='proto.Strategy.param6', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param7', full_name='proto.Strategy.param7', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param8', full_name='proto.Strategy.param8', index=7,
      number=8, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=266,
)


_ECONAGENT = _descriptor.Descriptor(
  name='EconAgent',
  full_name='proto.EconAgent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='aid', full_name='proto.EconAgent.aid', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inventory', full_name='proto.EconAgent.inventory', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='proto.EconAgent.strategy', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=364,
)


_INGREDIENT = _descriptor.Descriptor(
  name='Ingredient',
  full_name='proto.Ingredient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='proto.Ingredient.item_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='proto.Ingredient.count', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=410,
)


_RECIPE = _descriptor.Descriptor(
  name='Recipe',
  full_name='proto.Recipe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Recipe.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_item_id', full_name='proto.Recipe.output_item_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ingredients', full_name='proto.Recipe.ingredients', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=496,
)


_WORLD = _descriptor.Descriptor(
  name='World',
  full_name='proto.World',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='armors', full_name='proto.World.armors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crafting_materials', full_name='proto.World.crafting_materials', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recipes', full_name='proto.World.recipes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=498,
  serialized_end=607,
)

_INVENTORY.fields_by_name['items'].message_type = _ITEM
_ECONAGENT.fields_by_name['inventory'].message_type = _INVENTORY
_ECONAGENT.fields_by_name['strategy'].message_type = _STRATEGY
_RECIPE.fields_by_name['ingredients'].message_type = _INGREDIENT
_WORLD.fields_by_name['armors'].message_type = _ITEM
_WORLD.fields_by_name['crafting_materials'].message_type = _ITEM
_WORLD.fields_by_name['recipes'].message_type = _RECIPE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['Inventory'] = _INVENTORY
DESCRIPTOR.message_types_by_name['Strategy'] = _STRATEGY
DESCRIPTOR.message_types_by_name['EconAgent'] = _ECONAGENT
DESCRIPTOR.message_types_by_name['Ingredient'] = _INGREDIENT
DESCRIPTOR.message_types_by_name['Recipe'] = _RECIPE
DESCRIPTOR.message_types_by_name['World'] = _WORLD

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.Item)
  ))
_sym_db.RegisterMessage(Item)

Inventory = _reflection.GeneratedProtocolMessageType('Inventory', (_message.Message,), dict(
  DESCRIPTOR = _INVENTORY,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.Inventory)
  ))
_sym_db.RegisterMessage(Inventory)

Strategy = _reflection.GeneratedProtocolMessageType('Strategy', (_message.Message,), dict(
  DESCRIPTOR = _STRATEGY,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.Strategy)
  ))
_sym_db.RegisterMessage(Strategy)

EconAgent = _reflection.GeneratedProtocolMessageType('EconAgent', (_message.Message,), dict(
  DESCRIPTOR = _ECONAGENT,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.EconAgent)
  ))
_sym_db.RegisterMessage(EconAgent)

Ingredient = _reflection.GeneratedProtocolMessageType('Ingredient', (_message.Message,), dict(
  DESCRIPTOR = _INGREDIENT,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.Ingredient)
  ))
_sym_db.RegisterMessage(Ingredient)

Recipe = _reflection.GeneratedProtocolMessageType('Recipe', (_message.Message,), dict(
  DESCRIPTOR = _RECIPE,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.Recipe)
  ))
_sym_db.RegisterMessage(Recipe)

World = _reflection.GeneratedProtocolMessageType('World', (_message.Message,), dict(
  DESCRIPTOR = _WORLD,
  __module__ = 'econ_pb2'
  # @@protoc_insertion_point(class_scope:proto.World)
  ))
_sym_db.RegisterMessage(World)


# @@protoc_insertion_point(module_scope)
